// <auto-generated />
using System;
using KomOchHämta.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KomOchHämta.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230829092338_Added Products")]
    partial class AddedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KomOchHämta.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 8, 29, 11, 23, 37, 905, DateTimeKind.Local).AddTicks(9265),
                            Description = "Dyr",
                            Image = "Bild1",
                            ProductName = "Lampa"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 8, 29, 11, 23, 37, 905, DateTimeKind.Local).AddTicks(9365),
                            Description = "Billig",
                            Image = "Bild2",
                            ProductName = "Soffa"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 8, 29, 11, 23, 37, 905, DateTimeKind.Local).AddTicks(9368),
                            Description = "Rea",
                            Image = "Bild3",
                            ProductName = "Stol"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
